services:
  web:
    build:
      context: .
    command: "mkdocs serve --dev-addr=0.0.0.0:5001"
    restart: always
    ports:
      - 5001:5001
    volumes:
      - ./docs:/app/docs
      - ./overrides:/app/overrides
      # - ./mkdocs.yml:/app/mkdocs.yml

  # docs:
  #   image: python:latest
  #   volumes:
  #     - ./docs:/docs
  #     - ./overrides:/overrides
  #     # - ./requirements.txt:/requirements.txt
  #     # - ./mkdocs.yml:/mkdocs.yml
  #   # command: >
  #   #   sh -c " pip install mkdocs-material &&
  #   #           mkdocs serve --dev-addr=0.0.0.0:5000"
  #   command: "mkdocs serve --dev-addr=0.0.0.0:5000"
  #   ports:
  #     - 5000:5000




# version: '3.8'
# services:
#   mkdocs:
#     build: .
#     # image: squidfunk/mkdocs-material
#     # command: --serve
#     volumes:
#       - .:/docs
#     ports:
#       - "8080:8000"
#     environment:
#       - PWD=/docs
#     stdin_open: true
#     tty: true