version: '3.9'
services:
  web:
    build:
      context: .
    command: "serve --dev-addr=0.0.0.0:8082"
    restart: always
    ports:
      - 8082:8082
    volumes:
      - .:/docs






# version: '3.8'
# services:
#   mkdocs:
#     build: .
#     # image: squidfunk/mkdocs-material
#     # command: --serve
#     volumes:
#       - .:/docs
#     ports:
#       - "8080:8000"
#     environment:
#       - PWD=/docs
#     stdin_open: true
#     tty: true