services:
  # web:
  #   build:
  #     context: .
  #   command: "mkdocs serve --dev-addr=0.0.0.0:5000"
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./docs:/docs
  #     - ./overrides:/overrides
  #     - ./mkdocs.yml:/mkdocs.yml

  docs:
    image: python:latest
    volumes:
      - ./docs:/docs
      - ./overrides:/overrides
      - ./mkdocs.yml:mkdocs.yml
      - ./requirements.txt:requirements.txt
    command: >
      sh -c " pip install -r requirements.txt &&
              mkdocs serve --dev-addr=0.0.0.0:5000"
    ports:
      - 5000:5000




# version: '3.8'
# services:
#   mkdocs:
#     build: .
#     # image: squidfunk/mkdocs-material
#     # command: --serve
#     volumes:
#       - .:/docs
#     ports:
#       - "8080:8000"
#     environment:
#       - PWD=/docs
#     stdin_open: true
#     tty: true